### ISSUE TITLE
Questions about the some differences in files

### ISSUE THREAD

**Issue by eunji00-kim** [addb-swstarlab/TADA#1]
Thank you for sharing your code.

Looking at the TADA.ipynb and TADA_BB.ipynb, there are many similarities, but there are also differences.
I wonder why this difference occurred.

Also, I would like to know additional difference between TADA AA and TADA BB datasets.

Thank you.

**Comment by Kwon-sein** [comment]
Hi!
First of all, thank you for your interest in my code.

The TADA.ipynb file is that was tested on mysql's YCSB AA workload, and TADA_BB.ipynb is a file that was tested on mysql's YCSB BB workload.

The difference between YCSB AA and BB is that, as written in readme.md, **AA is a workload with a read ratio of 50 and a write ratio of 50**.

**BB is a read heavy** workload with a **read rate of 95% and a write rate of 5%**.

I hope the answer was helpful and thank you.
